// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aogegjtluttpgbkqciod.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvZ2VnanRsdXR0cGdia3FjaW9kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0ODk1NDEsImV4cCI6MjA3MDA2NTU0MX0.1xS7CpqvjsNYN4PxfrlU-QI0Wz7lo_n5Z1tw3Ablovs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});